services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7772:7772"
    volumes:
      - ./logs:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
