basePath: /api/v1
host: compile.prodonik.uz
info:
  contact: {}
  description: API for managing programming languages and compiling code
  title: Online Compiler API
  version: "1.0"
paths:
  /languages:
    get:
      description: Returns language-script pairs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve base Hello World scripts for all supported languages
      tags:
      - languages
swagger: "2.0"
