basePath: /
definitions:
  github_com_ruziba3vich_online_compiler_api_gateway_internal_dto.Language:
    properties:
      name:
        type: string
    type: object
host: 217.76.51.104:7772
info:
  contact: {}
  description: API for managing programming languages and compiling code
  title: Online Compiler API
  version: "1.0"
paths:
  /languages:
    get:
      description: Gets a list of all programming languages in the system
      produces:
      - application/json
      responses:
        "200":
          description: List of languages
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve all programming languages
      tags:
      - languages
    post:
      consumes:
      - application/json
      description: Adds a new programming language to the system
      parameters:
      - description: Language name
        in: body
        name: language
        required: true
        schema:
          $ref: '#/definitions/github_com_ruziba3vich_online_compiler_api_gateway_internal_dto.Language'
      produces:
      - application/json
      responses:
        "201":
          description: Language created successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict, language already exists
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new programming language
      tags:
      - languages
swagger: "2.0"
